name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+3

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  url_launcher: ^6.1.10
  syncfusion_flutter_datepicker: ^20.4.52
  intl: ^0.18.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  liquid_progress_indicator: ^0.4.0
  direct_select: "^1.0.3"
  cupertino_progress_bar: ^0.2.0
  firebase_messaging: ^14.4.0
  firebase_analytics: ^10.2.0

  awesome_notifications: ^0.6.19
  intl_phone_field: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  email_otp: ^2.0.1
  

dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/task_nb.png"
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/download-1-1.png
    - assets/page-1/images/download-1-1-GN4.png
    - assets/page-1/images/download-1-2.png
    - assets/page-1/images/download-removebg-preview-1.png
    - assets/page-1/images/download-1-1-Qdv.png
    - assets/page-1/images/download-removebg-preview-1-4LQ.png
    - assets/page-1/images/duskbin-removebg-preview-5.png
    - assets/page-1/images/download-1-1-nBr.png
    - assets/page-1/images/download-removebg-preview-1-3sn.png
    - assets/page-1/images/download-1-1-fLU.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-5Gk.png
    - assets/page-1/images/duskbin-removebg-preview-2.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-iSC.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-bF6.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-1.png
    - assets/page-1/images/download-1-1-KAQ.png
    - assets/page-1/images/download-1-1-zKi.png
    - assets/page-1/images/email-logo-png-27-2.png
    - assets/page-1/images/download-removebg-preview-1-TDJ.png
    - assets/page-1/images/download-1-1-1kc.png
    - assets/page-1/images/download-removebg-preview-1-Nr4.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-2vc.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-3Ap.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-2.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-2-KjE.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-bPE.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-wap.png
    - assets/page-1/images/download-1-1-uqa.png
    - assets/page-1/images/download-1-1-TMJ.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-Ysr.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-GDW.png
    - assets/page-1/images/download-1-1-oeg.png
    - assets/page-1/images/duskbin-removebg-preview-3.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-2.png
    - assets/page-1/images/transparent-lock-and-key-png-password-key-icon-3.png
    - assets/page-1/images/download-removebg-preview-1-9Cc.png
    - assets/page-1/images/download-removebg-preview-1-ek8.png
    - assets/page-1/images/images1-removebg-preview-1.png
    - assets/page-1/images/download-1-1-bmz.png
    - assets/page-1/images/download-1-1-Gn4.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-2-wtC.png
    - assets/page-1/images/download-1-1-ifJ.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-3-bg.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-2-XLU.png
    - assets/page-1/images/download-1-1-C4Y.png
    - assets/page-1/images/duskbin-removebg-preview-4.png
    - assets/page-1/images/download-1-1-PVi.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-2-qcc.png
    - assets/page-1/images/email-logo-png-27-1.png
    - assets/page-1/images/download-1-1-CUx.png
    - assets/page-1/images/download-1-1-pTi.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-hv8.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-dck.png
    - assets/page-1/images/download-removebg-preview-1-MDJ.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-2-Nsi.png
    - assets/page-1/images/download-removebg-preview-1-JmN.png
    - assets/page-1/images/download-removebg-preview-1-duz.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-iwS.png
    - assets/page-1/images/images1-removebg-preview-4.png
    - assets/page-1/images/duskbin-removebg-preview-2-3MS.png
    - assets/page-1/images/duskbin-removebg-preview-1.png
    - assets/page-1/images/duskbin-removebg-preview-5-KCU.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-bma.png
    - assets/page-1/images/email-logo-png-27-2-mgc.png
    - assets/page-1/images/transparent-lock-and-key-png-password-key-icon-3-VsW.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-2-Qbi.png
    - assets/page-1/images/duskbin-removebg-preview-3-A6L.png
    - assets/page-1/images/download-removebg-preview-1-VD2.png
    - assets/page-1/images/download-1-1-tkG.png
    - assets/page-1/images/download-removebg-preview-2.png
    - assets/page-1/images/download-removebg-preview-1-eJk.png
    - assets/page-1/images/download-removebg-preview-1-fKe.png
    - assets/page-1/images/images1-removebg-preview-5.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-3qJ.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-pgG.png
    - assets/page-1/images/download-removebg-preview-1-4rk.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-Ftc.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-xfr.png
    - assets/page-1/images/hd-wallpaper-homero-simpsons-homer-simpsons-phone-sad-the-simpsons-thumbnail-1-SUQ.png
    - assets/page-1/images/duskbin-removebg-preview-4-Nwi.png
    - assets/page-1/images/images1-removebg-preview-4-G24.png
    - assets/page-1/images/download-removebg-preview-1-BPv.png
    - assets/page-1/images/transparent-lock-and-key-png-password-key-icon-1.png
    - assets/page-1/images/transparent-lock-and-key-png-password-key-icon-2.png
    - assets/page-1/images/duskbin-removebg-preview-1-D8k.png
    - assets/page-1/images/b0b85cd8797638d0c80035f572b0cbd3-1-7qi.png
    - assets/page-1/images/download-removebg-preview-1-LVW.png
    - assets/page-1/images/download-removebg-preview-1-Etp.png
    - assets/page-1/images/download-removebg-preview-1-vmW.png
    - assets/page-1/images/download-removebg-preview-1-TJg.png
    - assets/page-1/images/pexels-monstera-63733052-1-1.png
    - assets/page-1/images/pexels-monstera-63733052-1-2-bg.png
    - assets/page-1/images/pexels-monstera-6373305-3-bg.png
    - assets/icon/task_nb.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
